mutation Login($input: LoginInput!) {
  login(input: $input) {
    accessToken
    user {
      id
      email
      firstName
      lastName
      phone
      role
      avatarUrl
      createdAt
      updatedAt
    }
  }
}

mutation Register($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    email
    firstName
    lastName
    role
    phone
  }
}

mutation RequestOtp($input: RequestOtpInput!) {
  requestOtp(input: $input) {
    phone
    expiresIn
    devCode
  }
}

mutation VerifyOtp($input: VerifyOtpInput!) {
  verifyOtp(input: $input)
}

mutation UpdateProfile($input: UpdateProfileInput!) {
  updateProfile(input: $input) {
    id
    firstName
    lastName
    phone
    avatarUrl
    role
    email
    createdAt
    updatedAt
  }
}

mutation ResetPassword($input: ResetPasswordInput!) {
  resetPassword(input: $input)
}

mutation DeleteMyAccount {
  deleteMyAccount {
    id
  }
}

query Me {
  me {
    id
    email
    firstName
    lastName
    phone
    role
    avatarUrl
  }
}
